import { createGemmaClient, createHeyAnonClient } from "@clocked/heyanon";
import { markJobCompleted, markJobFailed, prisma } from "@clocked/db";

export async function runHeyAnonEvidenceWorker() {
  const job = await prisma.job.findFirst({
    where: { kind: "HEYANON_EVIDENCE_QUERY", status: "QUEUED" },
    orderBy: { createdAt: "asc" }
  });

  if (!job) {
    return { ok: true, processed: 0 };
  }

  try {
    await prisma.job.update({
      where: { id: job.id },
      data: { status: "RUNNING", lockedAt: new Date(), attempts: { increment: 1 } }
    });

    const payload = job.payloadJson as Record<string, unknown>;
    const claim = typeof payload.claimId === "string"
      ? await prisma.claim.findUnique({ where: { id: payload.claimId } })
      : null;

    const heyanon = createHeyAnonClient({
      enableLiveCalls: process.env.HEYANON_ENABLE_LIVE_CALLS === "true"
    });
    const gemma = createGemmaClient({
      enableLiveCalls: process.env.HEYANON_ENABLE_LIVE_CALLS === "true"
    });

    const [delivery, context] = await Promise.all([
      heyanon.queryDeliveryEvidence({
        claimId: claim?.id,
        projectSlug: typeof payload.projectSlug === "string" ? payload.projectSlug : undefined,
        prompt: claim
          ? `Find public evidence for: ${claim.normalizedClaim}`
          : "Find public project evidence",
        sources: [],
        timeframe: {}
      }),
      gemma.askGemma({
        projectSlug: typeof payload.projectSlug === "string" ? payload.projectSlug : undefined,
        prompt: "Summarize public delivery context."
      })
    ]);

    if (claim) {
      await prisma.reviewItem.create({
        data: {
          kind: "HEYANON_EVIDENCE",
          payloadJson: {
            claimId: claim.id,
            evidenceType: "HEYANON_GEMMA_RESULT",
            summary: delivery.summary,
            rawJson: {
              deliverySummary: delivery.summary,
              deliveryEvidence: delivery.evidence,
              contextSummary: context.summary,
              contextEvidence: context.evidence
            }
          },
          reason: "Generated by HeyAnon evidence worker."
        }
      });
    }

    await markJobCompleted(job.id);
    return { ok: true, processed: 1 };
  } catch (error) {
    await markJobFailed(job.id, error instanceof Error ? error.message : "Unknown error");
    return { ok: false, processed: 0 };
  }
}
